name: Deploy to DigitalOcean Container Registry

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Check if ENV is set
        run: |
          if [ -z "${{ secrets.ENV }}" ]; then
            echo "ENV secret is not set or is empty."
          else
            echo "ENV secret is set."
          fi
        shell: bash

      - name: Log in to DigitalOcean Container Registry
        uses: docker/login-action@v3
        with:
          registry: registry.digitalocean.com
          username: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          password: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./apps/upload_service/Dockerfile
          push: true
          tags: registry.digitalocean.com/${{ secrets.REGISTRY_NAME }}/upload_service:latest
          build-args: |
            ENV=${{ secrets.ENV }}

      - name: Logout from DigitalOcean Container Registry
        if: always()
        run: docker logout registry.digitalocean.com
