name: Deploy to DigitalOcean Container Registry

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Show ENV and list config files
        run: |
          echo "ENV is set to $ENV"
          ls -l ./apps/upload_service/
        env:
          ENV: prod

      - name: Log in to DigitalOcean Container Registry
        uses: docker/login-action@v3
        with:
          registry: registry.digitalocean.com
          username: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          password: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./apps/upload_service/Dockerfile
          push: true
          tags: registry.digitalocean.com/creotip-hub/upload_service:latest
          target: prod
          build-args: |
            ENV=prod

      - name: Logout from DigitalOcean Container Registry
        if: always()
        run: docker logout registry.digitalocean.com
